// Family tree of Matěj Veselý – data (derived from RODOKMEN_stav_vyzkumu.md; update with every research iteration)
// cert: M = read in a parish/civil register, D = other document, R = family tradition, K = candidate / unverified
window.RODOKMEN = {
  updated: "6. 10. 2026",
  root: "matej",
  lines: {
    vesely: "Veselý",
    woron: "Woroň",
    chmielek: "Chmielek",
    pacik: "Pacík",
    matusu: "Matůšů",
    struz: "Struž",
    jirik: "Jiřík",
    opolony: "Opoloný"
  },
  people: [
    { id: "matej", name: "Matěj Veselý", line: "vesely", cert: "D",
      b: { date: "15. 1. 1986", year: 1986, place: "Ostrava" },
      father: "radim", mother: "jana",
      notes: ["Výchozí osoba rodokmenu.", "Nemá sourozence."] },

    // ── Veselý ─────────────────────────────────────────
    { id: "radim", name: "Radim Veselý", line: "vesely", cert: "R",
      b: { date: "1961", year: 1961, place: "pravděpodobně Frýdek-Místek" },
      father: "svaton", mother: "marta",
      marriage: "22. 6. 1985 – s Janou Pacíkovou (údaj rodiny)",
      notes: ["Sestra Miluše Kempná, roz. Veselá (*19. 4. 1958 Ostrava-Fifejdy), manžel Rostislav Kempný, děti Rostislav a Barbora."] },
    { id: "jana", name: "Jana Veselá", maiden: "Pacíková", line: "pacik", cert: "D",
      b: { date: "23. 6. 1962", year: 1962, place: "Ostrava" },
      father: "rudolf1936", mother: "margareta",
      notes: ["Sourozenci: Rudolf Pacík (*29. 3. 1961 Ostrava, †3. 8. 2018 Ostrava, pohřben v Chuchelné), Tomáš Pacík."] },
    { id: "svaton", cause: "zánět plic", name: "Svatoň Veselý", line: "vesely", cert: "D",
      b: { date: "17. 9. 1933", year: 1933, place: "Kežmarok (Slovensko)" },
      d: { date: "19. 9. 2007", year: 2007, place: "FN Ostrava-Poruba" },
      father: "karelV", mother: "annaP",
      marriage: "28. 9. 1957, Slezská Ostrava (kostel sv. Josefa) – s Martou Woroňovou",
      notes: ["Kolem roku 1940 se s rodiči přestěhoval z Kežmarku do Uherského Brodu (vyprávění babičky Marty, opakovaně).", "Rodinný hrob v Hodoňovicích.", "Sourozenci: Karel, Růženka.", "V poznámkách se objevuje Uherský Brod 1940 – význam neověřen.", "Odpis rodného listu vyžádán z Matričného úradu Kežmarok (6. 10. 2026)."] },
    { id: "karelV", scans: [{"f": "img/1930_scitani_karel_vesely.jpg", "t": "Sčítání 1930, Kežmarok, Hlavná ul. 7 (ř. 8)"}], name: "Karel (Karol) Veselý", line: "vesely", cert: "D",
      b: { date: "4. 10. 1904", year: 1904, place: "Plavnice / Planá (?), okr. České Budějovice, Čechy" },
      occ: "úředník (Offizial) Nemocenské pojišťovny v Kežmarku; 1934–37 městský zastupitel za Čsl. sociálně demokratickou stranu",
      marriage: "mezi 12/1930 a 9/1933 – s Annou Plachou (v roce 1930 oba svobodní)",
      notes: ["Sčítání 2. 12. 1930: podnájemník v domě Elsy Hegenbart, Hauptgasse (Hlavná ul.) č. 7; svobodný; národnost česká; bez vyznání; do Kežmarku přišel 19. 11. 1922 z Plzně; domovská obec „Todňany“ (?), okr. Č. Budějovice – čtení nejisté.", "Karpathen-Post: 27. 10. 1934 náhradník kandidátky ČSSD („Karol Vesely, Beamter“), 16. 2. 1935 složil slib jako městský zastupitel, člen finanční komise; 1936 bydliště Kežmarok, Sihoť (Insel) 15; 1937 jednatel místní skupiny KČST (Klub čs. turistů).", "Dřívější odhad narození „cca 1903“ opraven podle sčítání.", "Kandidát: Karel Veselý, předseda ONV Uherský Brod 1945 (neověřeno)."],
      sources: ["Sčítání lidu 1930, Kežmarok, arch 321/56 (Slovakiana, objekt cair-ko11kbp)", "Karpathen-Post 27. 10. 1934, 8. 12. 1934, 26. 1. 1935, 16. 2. 1935, 5. 12. 1936, 27. 11. 1937 (difmoe.eu)"] },
    { id: "annaP", scans: [{"f": "img/1930_scitani_anna_placha.jpg", "t": "Sčítání 1930, Kežmarok, Trímostová ul. 57 (ř. 5)"}], name: "Anna Veselá", maiden: "Plachá", line: "vesely", cert: "D",
      b: { date: "5. 12. 1907", year: 1907, place: "Věrovany, okr. Tovačov, Morava" },
      occ: "pokladní (1930, v řeznictví švagra Methoda Krejsy)",
      notes: ["Sčítání 1930: žila v domácnosti sestry Terezie (*2. 1. 1902 Věrovany) a jejího muže Methoda Krejsy, řezníka a uzenáře (*1895 Citov), Kežmarok, Trímostová ul. 57; do Kežmarku přišla 1930 z Věrovan; svobodná; římskokatolická; národnost česká.", "Bratr František Plachý *17. 8. 1906 Věrovany, řeznický pomocník v Kežmarku od 1925.", "Rodiče zatím neznámé → matrika Věrovany (ZA Opava, pobočka Olomouc)."],
      sources: ["Sčítání lidu 1930, Kežmarok, arch 321/242 (Slovakiana, objekt cair-ko1515u)"] },

    // ── Woroň / Chmielek ───────────────────────────────
    { id: "marta", name: "Marta Veselá", maiden: "Woroňová", line: "woron", cert: "D",
      b: { date: "4. 12. 1939", year: 1939, place: "Ostrava" },
      father: "ludvik", mother: "honorata", alive: true,
      notes: ["Žije. Vyrůstala v Ostravě 8.", "Sestra Libuše Randulová (manžel Josef, děti Dušan a Tomáš); sourozenci Miloslava a Jaroslav zemřeli před jejím narozením."] },
    { id: "ludvik", scans: [{"f": "img/1903_krest_ludvik_woron.jpg", "t": "Křest 1903 (fol. 171)"}], name: "Ludvík Woroň", line: "woron", cert: "M",
      b: { date: "18. 7. 1903", year: 1903, place: "Polská (Slezská) Ostrava č. 69, Kamenec" },
      d: { date: "21. 8. 1986", year: 1986 },
      father: "andreas", mother: "margaretha",
      marriage: "9. 8. 1925 – s Honoratou Chmielkovou (poznámka v křestní matrice; oba vystoupili z církve 19. 2. 1925 – sňatek zřejmě civilní, zápis zatím nenalezen)",
      notes: ["Pokřtěn 20. 7. 1903. Rodina uváděla narození 19. 8. 1903 – matrika říká 18. 7.", "Kmotři: Tomáš(?) Woroň, horník na Hranečníku, a Josefa, jeho manželka."],
      sources: ["ř.-k. fara Slezská Ostrava, N 1902–1905 (SO VII 36), fol. 171 – ZA Opava"] },
    { id: "honorata", scans: [{"f": "img/1903_krest_honorata.jpg", "t": "Křest 1903"}], name: "Honorata Woroňová", maiden: "Chmielková", line: "chmielek", cert: "M",
      b: { date: "10. 9. 1903", year: 1903, place: "Polská (Slezská) Ostrava č. 17" },
      d: { date: "12. 8. 1968", year: 1968 },
      father: "stanislaus", mother: "helenaD",
      notes: ["Pokřtěna 19. 9. 1903 jako Honorata Maria.", "Poznámka v matrice: oddána 9. 8. 1925 s Ludvíkem Woroněm."],
      sources: ["ř.-k. fara Slezská Ostrava, N 1902–1905 (SO VII 36), sken 101 – ZA Opava"] },
    { id: "andreas", scans: [{"f": "img/1903_krest_ludvik_woron.jpg", "t": "Křest syna Ludvíka 1903"}], name: "Ondřej (Andreas) Woroń", line: "woron", cert: "M",
      b: { date: "19. 10. 1869 (?)", year: 1869, place: "Lednica Dolna, okr. Wieliczka (Halič)" },
      occ: "horník",
      marriage: "24. 8. 1896, Wieliczka (dle zápisu v Ostravě) – s Markétou Włudyka; ve Wieliczce (město, Lednica Dolna, Siercza) ani v Rajbrotu zatím nenalezen",
      notes: ["Kandidáti na rodiče (K, sňatek v oddacích Lednice 1835–1858 není – zřejmě ve farnosti nevěsty nebo ve městě Wieliczka): Kasper (Gaspar) Woroń × Katarzyna Szarek, Lednica Dolna č. 107 (děti Zofia *1857, Jan, Franciszek); méně pravděpodobně Jakub Woroń (*1825, syn Franciszka a Wiktorie Witkowské), solivarník, × Małgorzata Dębska / Marianna Gabryś.", "Křest 1869 není online (venkovské křty farnosti Wieliczka po 1840 nejsou v CAAK) – nutná žádost na faru sv. Klemense ve Wieliczce.", "Data ze sloupců křestního zápisu syna čtena nejistě.", "Rod Woroń je v Lednici Dolní doložen už kolem roku 1780 (strom FamilySearch)."],
      sources: ["SO VII 36, fol. 171"] },
    { id: "margaretha", scans: [{"f": "img/1858_krest_malgorzata_wludyka.jpg", "t": "Křest 12. 7. 1858, Rajbrot č. 13"}, {"f": "img/1903_krest_ludvik_woron.jpg", "t": "Křest syna Ludvíka 1903"}], name: "Markéta (Małgorzata) Woroń", maiden: "Włudyka", line: "woron", cert: "M",
      b: { date: "12. 7. 1858", year: 1858, place: "Rajbrot č. 13, okr. Bochnia (Halič)" },
      father: "franzW", mother: "mariannaDr",
      notes: ["Dcera Františka Włudyky, rolníka v Rajbrotu, a Marianny roz. Drąg.", "Dřívější čtení data narození 17. 7. 1875 bylo chybné – v ostravském zápisu stojí 12/7 58, což přesně sedí s křtem v Rajbrotu.", "Na okraji křtu poznámka o výpisu z 1. 7. 1896 – zřejmě pro sňatek.", "Bratr Jan Włudyka se oženil v Rajbrotu 19. 11. 1896.", "Rodinné poznámky ji chybně uváděly jako „Helenu Chmielkovou“."],
      sources: ["Księgi metrykalne parafii Rajbrot, U 1842–1862, 1858 č. 48, skan 082 (Skanoteka PTG, zespół 7020, sygn. 3530)", "SO VII 36, fol. 171"] },
    { id: "franzW", scans: [{"f": "img/1805_krest_franciszek_wludyka.jpg", "t": "Křest 6. 8. 1805"}, {"f": "img/1828_snatek_wludyka_drag.jpg", "t": "Sňatek 1828"}], name: "František (Franciszek) Włudyka", line: "woron", cert: "M",
      b: { date: "6. 8. 1805", year: 1805, place: "Rajbrot č. 269, okr. Bochnia" },
      d: { date: "před 1896", year: 1890, approx: true },
      father: "valentinW", mother: "reginaM",
      occ: "rolník (agricola) v Rajbrotu",
      marriage: "1828 (únor?), Rajbrot č. 269 – s Mariannou Drąg (on 24 let, ona 15)",
      notes: ["Psán též Włodyka / Wludyka.", "V roce 1896 už nežil („def. Francisci“)."],
      sources: ["Rajbrot U 1800–1807, skan 042; index U 1680–1923 skan 120", "Rajbrot M 1788–1840, 1828 č. 11, skan 042"] },
    { id: "mariannaDr", scans: [{"f": "img/1828_snatek_wludyka_drag.jpg", "t": "Sňatek 1828"}], name: "Marianna Włudyka", maiden: "Drąg", line: "woron", cert: "M",
      b: { date: "cca 1813", year: 1813, approx: true, place: "Rajbrot" },
      father: "szymonD", mother: "mariannaFi",
      notes: ["Při sňatku 1828 bylo nevěstě 15 let."],
      sources: ["Rajbrot M 1788–1840, skan 042", "křest dcery Małgorzaty 1858"] },
    { id: "valentinW", scans: [{"f": "img/1764_krest_valentin_wlodyka.jpg", "t": "Křest 13. 2. 1764"}], name: "Valentin (Walenty) Włodyka", line: "woron", cert: "M",
      b: { date: "13. 2. 1764", year: 1764, place: "Rajbrot" },
      father: "janWl", mother: "konstancjaK",
      marriage: "10. 11. 1787 Rajbrot – s Reginou Mulkovou (jen podle indexu; zápis, kniha tom 1 s. 1, není naskenován)",
      notes: ["Křest: „Valentinum Joannis Włodyka et Constantiae CL. Patrini fuere Valentinus Radzięta et Catharina Tapcyna Omnes de Raybroth“."],
      sources: ["Rajbrot U 1719–1767, s. 230, skan 122 (Skanoteka PTG id4946)", "index sňatků Rajbrot (sy7005, skan 053)"] },
    { id: "janWl", scans: [{"f": "img/1759_snatek_jan_wlodyka.jpg", "t": "Sňatek 25. 2. 1759"}], name: "Jan Włodyka", line: "woron", cert: "M",
      b: { date: "cca 1732 (?)", year: 1732, approx: true, place: "Rajbrot" },
      marriage: "25. 2. 1759 Rajbrot – s Konstancií Kanownik (Kanonikówna)",
      notes: ["Sňatek: „Matrimonium Contractum inter Joannem Włodyka et Constantiam Kanonikowna … praesentibus Jacobo Radzięta et Mathia Kanonik(?) Omnes de Raybroth“ – oddával Mathias Szymczakiewicz.", "Kandidát na křest: Jan, syn Jana a Barbary Włodykových, 28. 2. (?) 1732 (index s. 89); možný je i Jan syn Josefa a Reginy, 24. 5. 1728."],
      sources: ["Rajbrot M 1719–1760, s. 62, skan 033"] },
    { id: "konstancjaK", scans: [{"f": "img/1759_snatek_jan_wlodyka.jpg", "t": "Sňatek 25. 2. 1759"}], name: "Konstancie Włodyková", maiden: "Kanownik", line: "woron", cert: "M",
      b: { date: "?", year: 1738, approx: true, place: "Rajbrot" },
      sources: ["Rajbrot M 1719–1760, s. 62, skan 033"] },
    { id: "reginaM", name: "Regina Włodyka", maiden: "Mulka (?)", line: "woron", cert: "M",
      b: { date: "?", year: 1770, approx: true },
      notes: ["Dcera Matyáše (?) Mulky – čtení příjmení nejisté."],
      sources: ["křest syna Františka 1805", "křest vnučky Małgorzaty 1858"] },
    { id: "szymonD", scans: [{"f": "img/1812_snatek_drag_fitrzyk.jpg", "t": "Sňatek 4. 2. 1812"}], name: "Šimon (Szymon) Drąg", line: "woron", cert: "M",
      b: { date: "cca 1748", year: 1748, approx: true, place: "Rajbrot" },
      marriage: "4. 2. 1812 Rajbrot č. 191 – s Mariannou Fitrzyk (on 64letý vdovec, ona 36letá vdova)",
      notes: ["Oba šli do manželství podruhé; kandidát na 1. manželství: Szymon Drąg × Anna Gromała 1806 (index)."],
      sources: ["křest vnučky Małgorzaty 1858"] },
    { id: "mariannaFi", scans: [{"f": "img/1812_snatek_drag_fitrzyk.jpg", "t": "Sňatek 4. 2. 1812"}], name: "Marianna Drąg", maiden: "Fitrzyk", line: "woron", cert: "M",
      b: { date: "cca 1776", year: 1776, approx: true, place: "Rajbrot" },
      notes: ["Při sňatku 1812 vdova, 36 let."],
      sources: ["křest vnučky Małgorzaty 1858"] },
    { id: "stanislaus", scans: [{"f": "img/1903_krest_honorata.jpg", "t": "Křest dcery Honoraty 1903"}], name: "Stanislav (Stanislaus) Chmielek", line: "chmielek", cert: "M",
      b: { date: "7. 1. 1876 (?)", year: 1876, place: "Zagórzany, okr. Wieliczka (Halič)" },
      occ: "horník",
      marriage: "18. 9. 1903 (?) – s Helenou Dydowicz",
      notes: ["Kandidát (Geneteka): Stanisław Chmielek *1872, farnost Gdów (kam patří Zagórzany), syn Marcina Chmielka a Marianny Grzyb – rok nesedí s nejistým čtením 1876, neověřeno."],
      sources: ["SO VII 36, sken 101"] },
    { id: "helenaD", scans: [{"f": "img/1903_krest_honorata.jpg", "t": "Křest dcery Honoraty 1903"}], name: "Helena Chmielková", maiden: "Dydowicz", line: "chmielek", cert: "M",
      b: { date: "1. 9. 1884 (?)", year: 1884, place: "Rudno, okr. Tarnów (Halič)?" },
      father: "tomasD",
      notes: ["Dcera Tomáše Dydowicze, domkáře v Rudně.", "Kandidát (Geneteka): rod Dydowicz je doložen ve farnosti Szczucin / Mędrzechów (okr. Dąbrowa Tarnowska) – neověřeno.", "Toto je „Helena Chmielková“ z rodinných poznámek – matka Honoraty."],
      sources: ["SO VII 36, sken 101"] },
    { id: "tomasD", name: "Tomáš Dydowicz", line: "chmielek", cert: "M",
      b: { date: "?", year: 1855, approx: true, place: "Rudno, okr. Tarnów" },
      occ: "domkář (Gärtler)" },

    // ── Pacík ──────────────────────────────────────────
    { id: "rudolf1936", cause: "nezhoubný nádor krku", name: "Rudolf Pacík", line: "pacik", cert: "D",
      b: { date: "5. 6. 1936", year: 1936, place: "Nedašova Lhota" },
      d: { date: "3. 5. 2013", year: 2013, place: "Ostrava" },
      father: "frantisek1892", mother: "annaM",
      marriage: "cca 1960 – s Margaretou Stružovou",
      notes: ["Pohřben v Chuchelné.", "Starší sourozenci (matrika): František *16. 11. 1916, Františka *5. 1. 1919, Jan *23. 10. 1920, Alois *7. 11. 1922; sestra Marie, provd. Halamová (Orlová).", "Narození 1936 ještě není v archivu (100letá lhůta)."] },
    { id: "frantisek1892", scans: [{"f": "img/1892_narozeni_frantisek_pacik.jpg", "t": "Narození 14. 7. 1892"}, {"f": "img/1916_snatek_pacik_matusu.jpg", "t": "Sňatek 8. 2. 1916"}], name: "František Pacík", line: "pacik", cert: "M",
      b: { date: "14. 7. 1892", year: 1892, place: "Nedašova Lhota č. 5" },
      d: { date: "1965 (?)", year: 1965, approx: true },
      father: "jan1861", mother: "frantiskaT",
      occ: "dělník / domkář; 1916 domobranec",
      marriage: "8. 2. 1916, Nedašov – s Annou Matůšů",
      notes: ["Verze „zemřel v USA“ vyvrácena.", "Úmrtí 1965 jen podle stromu na Geni (neověřeno)."],
      sources: ["MZA Brno, N 4482 str. 49; O 4486 str. 67"] },
    { id: "annaM", scans: [{"f": "img/1916_snatek_pacik_matusu.jpg", "t": "Sňatek 8. 2. 1916"}], name: "Anna Pacíková", maiden: "Matůšů", line: "matusu", cert: "M",
      b: { date: "16. 4. 1894", year: 1894, place: "Nedašov č. 64" },
      d: { date: "1968 (?)", year: 1968, approx: true },
      father: "josefM", mother: "mariannaN",
      notes: ["Úmrtí 1968 jen podle stromu na Geni (neověřeno)."],
      sources: ["MZA Brno, N 4475 str. 126"] },
    { id: "jan1861", scans: [{"f": "img/1935_umrti_anna_valentova.jpg", "t": "Úmrtí 2. manželky Anny roz. Valentové 1935"}, {"f": "img/1892_narozeni_frantisek_pacik.jpg", "t": "Narození syna Františka 1892"}], cause: "zánět plic", name: "Jan Pacík", line: "pacik", cert: "M",
      b: { date: "30. 12. 1861", year: 1861, place: "Nedašova Lhota č. 5" },
      d: { date: "1. 5. 1912", year: 1912, place: "Nedašova Lhota č. 5" },
      father: "matej1832", mother: "mariannaK", occ: "domkář",
      marriage: "11. 7. 1887 – s Františkou Tomečkovou; 2. sňatek 1901 s Annou Valentovou z Poteče (*16. 4. 1872, †4. 1. 1935)",
      notes: ["Zemřel na zánět plic.", "Děti z 1. manželství: Jan 1888, Maria 1890, Ludvík 1891, František 1892, Alois 1894, Jan 1897, Františka 1899."],
      sources: ["MZA N 4481; O 4489; Z 4496"] },
    { id: "frantiskaT", scans: [{"f": "img/1892_narozeni_frantisek_pacik.jpg", "t": "Narození syna Františka 1892"}], cause: "otrava krve (gangréna ruky)", name: "Františka Pacíková", maiden: "Tomečková", line: "pacik", cert: "M",
      b: { date: "12. 9. 1862", year: 1862, place: "Nedašova Lhota" },
      d: { date: "12. 7. 1899", year: 1899, place: "Nedašova Lhota č. 5" },
      father: "frantisekT1819", mother: "annaB",
      notes: ["Zemřela na otravu krve (gangréna ruky)."], sources: ["MZA N 4481; Z 4495"] },
    { id: "matej1832", name: "Matěj Pacík", line: "pacik", cert: "M",
      b: { date: "17. 3. 1832", year: 1832, place: "Nedašova Lhota" },
      d: { date: "18. 10. 1903", year: 1903, place: "Nedašova Lhota č. 5" },
      father: "josef1798", mother: "veronikaV", occ: "domkář, tkadlec",
      marriage: "5. 5. 1856 – s Mariannou Kolínkovou", sources: ["MZA N 4481; O 4489; Z 4496"] },
    { id: "mariannaK", name: "Marianna Pacíková", maiden: "Kolínková", line: "pacik", cert: "M",
      b: { date: "cca 1830", year: 1830, approx: true, place: "Nedašova Lhota" },
      father: "josefK1797", mother: "katerinaM" },
    { id: "frantisekT1819", name: "František Tomeček", line: "pacik", cert: "M",
      b: { date: "16. 2. 1819", year: 1819, place: "Nedašova Lhota č. 6" },
      father: "janT", mother: "mariannaF", occ: "domkář / podsedník",
      marriage: "25. 2. 1851 – s Annou Bartošákovou (dispens pro příbuzenství 3. stupně)" },
    { id: "annaB", name: "Anna Tomečková", maiden: "Bartošáková", line: "pacik", cert: "M",
      b: { date: "cca 1826", year: 1826, approx: true, place: "Nedašova Lhota" },
      father: "vaclavB", mother: "mariannaVn" },
    { id: "josef1798", scans: [{"f": "img/1798_krest_josef_pacik.jpg", "t": "Křest 2. 2. 1798"}, {"f": "img/1826_snatek_josef_pacik.jpg", "t": "Sňatek 24. 1. 1826"}], name: "Josef Pacík", line: "pacik", cert: "M",
      b: { date: "2. 2. 1798", year: 1798, place: "Nedašova Lhota č. 5" },
      father: "matous1760", mother: "marinaM", occ: "domkář",
      marriage: "24. 1. 1826 – s Veronikou Vaňkovou", sources: ["MZA N 4473; O 4489"] },
    { id: "veronikaV", scans: [{"f": "img/1799_krest_veronika_vankova.jpg", "t": "Křest 2. 4. 1799"}, {"f": "img/1826_snatek_josef_pacik.jpg", "t": "Sňatek 24. 1. 1826"}], name: "Veronika Pacíková", maiden: "Vaňková", line: "pacik", cert: "M",
      b: { date: "2. 4. 1799", year: 1799, place: "Nedašova Lhota č. 22" }, father: "tomasV", mother: "annaKol",
      notes: ["Při sňatku 1826 udáno 22 let (tj. cca 1804) – věk v oddacím zápisu je nepřesný; křest 1799 je ve stejném domě u stejných rodičů.", "Starší sestra Barbara *19. 9. 1796."] },
    { id: "tomasV", scans: [{"f": "img/1778_snatek_tomas_anna_K.jpg", "t": "Kandidát: sňatek 1. 6. 1778"}, {"f": "img/1799_krest_veronika_vankova.jpg", "t": "Křest dcery Veroniky 1799"}], name: "Tomáš Vaněk", line: "pacik", cert: "M",
      notes: ["Kandidát (K): sňatek 1. 6. 1778, Lhota č. 24 – „Thomas filius Georgii Fojtík cum … Anna filia post † Georgium Kolínek“ (4012 img 191). Fojtíkové mu opakovaně stojí za kmotry – Vaněk mohl být původně Fojtík (podobně jako Pacík). Proti: Anna by v roce 1799 měla cca 40 let. Neověřeno."],
      b: { date: "?", year: 1770, approx: true }, occ: "zedník (Maurer), Nedašova Lhota č. 22",
      marriage: "cca 1790–1796 – s Annou Kolínkovou (zápis zatím nenalezen)" },
    { id: "annaKol", scans: [{"f": "img/1799_krest_veronika_vankova.jpg", "t": "Křest dcery Veroniky 1799"}], name: "Anna Vaňková", maiden: "Kolínková", line: "pacik", cert: "M",
      b: { date: "?", year: 1772, approx: true }, sources: ["křest dcery Veroniky 1799 (N 4473, img 140)"] },
    { id: "josefK1797", scans: [{"f": "img/1821_snatek_kolinek.jpg", "t": "Sňatek 25. 2. 1821"}], name: "Josef Kolínek", line: "pacik", cert: "M",
      b: { date: "9. 2. 1797", year: 1797, place: "Nedašova Lhota č. 60" },
      father: "jakubK", mother: "marinaA", occ: "domkář",
      marriage: "25. 2. 1821 – s Kateřinou Měřičkovou" },
    { id: "katerinaM", scans: [{"f": "img/1794_krest_katerina_merickova.jpg", "t": "Křest 17. 9. 1794"}, {"f": "img/1821_snatek_kolinek.jpg", "t": "Sňatek 25. 2. 1821"}], name: "Kateřina Kolínková", maiden: "Měřičková", line: "pacik", cert: "M",
      b: { date: "17. 9. 1794", year: 1794, place: "Nedašova Lhota č. 9" },
      notes: ["Nemanželská dcera Kateřiny Měřičkové (Mirzičkin) z Lhoty; kmotři Johann Dorniak (?) a Marina Kolínková.", "Kandidát na příbuzného matky: Bartoš Měřička, zahradník v Lhotě č. 30 (1797–1802)."],
      sources: ["N 4473, img 135"] },
    { id: "jakubK", scans: [{"f": "img/1770_snatek_jakub_kolinek.jpg", "t": "1. sňatek 23. 5. 1770"}, {"f": "img/1787_snatek_kolinek_adamkova.jpg", "t": "Sňatek 16. 9. 1787 (O 4023)"}, {"f": "img/1787_snatek_kolinek_lat.jpg", "t": "Sňatek 1787 – latinský zápis (4012)"}], name: "Jakub Kolínek", line: "pacik", cert: "M",
      b: { date: "cca 1750", year: 1750, approx: true }, occ: "podruh (Inmann) v Nedašově Lhotě",
      marriage: "16. 9. 1787, Ned. Lhota č. 8 – jako vdovec (37 let) s Marinou Adamkovou",
      notes: ["1. sňatek 23. 5. 1770: „Jacobus Kolínek rusticus Chota cum hon. virgine Anna filia Martini Lišák(?) Bilnicio“, Lhota č. 12 (4012 img 183); děti Kateřina 1774, Barbara 1777."],
      sources: ["O 4023 img 123; 4012 img 204"] },
    { id: "marinaA", scans: [{"f": "img/1787_snatek_kolinek_adamkova.jpg", "t": "Sňatek 16. 9. 1787"}], name: "Marina Kolínková", maiden: "Adamková", line: "pacik", cert: "M",
      b: { date: "cca 1765", year: 1765, approx: true },
      notes: ["Dcera † Martina Adamka z Lhoty (při sňatku 1787 22 let). Martin Adamek se jinde objevuje jako „caupo“ – krčmář (z Nedašova)."] },
    { id: "janT", scans: [{"f": "img/1776_krest_jan_tomecek.jpg", "t": "Křest 8. 12. 1776"}], name: "Jan Tomeček", line: "pacik", cert: "M",
      mother: "katerinaTo",
      b: { date: "8. 12. 1776", year: 1776, place: "Nedašova Lhota č. 1" }, father: "josefT", occ: "sedlák",
      marriage: "6. 10. 1800, Ned. Lhota č. 1 – s Mariannou Fojtíkovou (on 23, ona 18)",
      sources: ["O 4023 img 126"] },
    { id: "josefT", name: "Josef Tomeček", line: "pacik", cert: "M",
      b: { date: "?", year: 1745, approx: true }, occ: "sedlák v Nedašově Lhotě",
      notes: ["Manželka Kateřina (u dětí 1773 a 1776); Veronika, žena Josefa Tomečka v roce 1761, byla buď jeho dřívější manželkou, nebo jde o jiného Josefa. Je otcem Jana Tomečka (*cca 1777) i Mariny Vaňkové (*cca 1773) – rodokmen se tu dvakrát sbíhá; to vysvětluje dispens pro příbuzenství 3. stupně při pozdějším sňatku 1851."] },
    { id: "mariannaF", name: "Marianna Tomečková", maiden: "Fojtíková", line: "pacik", cert: "M",
      father: "martinFo", mother: "rosinaFo",
      b: { date: "cca 1782", year: 1782, approx: true }, notes: ["Dcera sedláka Martina Fojtíka (sňatek 1800: 18 let)."] },
    { id: "vaclavB", scans: [{"f": "img/1822_snatek_bartosak.jpg", "t": "Sňatek 5. 2. 1822"}], name: "Václav Bartošák", line: "pacik", cert: "M",
      b: { date: "cca 1798", year: 1798, approx: true }, occ: "podsedník", marriage: "5. 2. 1822 – s Mariannou Vaňkovou",
      notes: ["Podle oddacího zápisu syn Josefa Bartošáka a Anny roz. Bartošákové (?).", "Kandidát: 1. 8. 1802 pokřtěn nemanželský Václav, syn Anny Bartoškové z Lhoty č. 50 (4473 img 143) – věk nesedí, neověřeno."] },
    { id: "mariannaVn", scans: [{"f": "img/1802_krest_marianna_vankova.jpg", "t": "Křest 13. 10. 1802"}, {"f": "img/1822_snatek_bartosak.jpg", "t": "Sňatek 5. 2. 1822"}], name: "Marianna Bartošáková", maiden: "Vaňková", line: "pacik", cert: "M",
      b: { date: "13. 10. 1802", year: 1802, place: "Nedašova Lhota č. 31" }, father: "pavelV", mother: "marinaTo",
      sources: ["N 4473 img 144"] },
    { id: "pavelV", scans: [{"f": "img/1772_krest_pavel_vanek.jpg", "t": "Křest 22. 6. 1772"}, {"f": "img/1792_snatek_vanek_tomeckova.jpg", "t": "Sňatek 25. 11. 1792"}], name: "Pavel Vaněk", line: "pacik", cert: "M",
      father: "mikulasV", mother: "marinaVa",
      b: { date: "22. 6. 1772", year: 1772, place: "Nedašova Lhota č. 25" }, occ: "sedlák v Nedašově Lhotě",
      marriage: "25. 11. 1792, Ned. Lhota č. 38 – s Marinou Tomečkovou (on 21, ona 19); svědci Bartoš Fojtík a Martin Tomeček",
      notes: ["Kmotři Josef Tomeček a Anna Fojtíková; sestra Anna *1782.", "Syn Mikuláše Vaňka, sedláka z Lhoty."], sources: ["O 4023 img 124"] },
    { id: "marinaTo", scans: [{"f": "img/1773_krest_marina_tomeckova.jpg", "t": "Křest 30. 3. 1773"}, {"f": "img/1792_snatek_vanek_tomeckova.jpg", "t": "Sňatek 25. 11. 1792"}], name: "Marina Vaňková", maiden: "Tomečková", line: "pacik", cert: "M",
      mother: "katerinaTo",
      b: { date: "30. 3. 1773", year: 1773, place: "Nedašova Lhota č. 1" }, father: "josefT",
      sources: ["O 4023 img 124"] },
    { id: "mikulasV", scans: [{"f": "img/1772_krest_pavel_vanek.jpg", "t": "Křest syna Pavla 1772"}], name: "Mikuláš Vaněk", line: "pacik", cert: "M",
      b: { date: "?", year: 1745, approx: true }, occ: "sedlák v Nedašově Lhotě" },
    { id: "marinaVa", scans: [{"f": "img/1772_krest_pavel_vanek.jpg", "t": "Křest syna Pavla 1772"}], name: "Marina Vaňková", line: "pacik", cert: "M",
      b: { date: "?", year: 1748, approx: true }, notes: ["Rodné příjmení neznámé."] },
    { id: "katerinaTo", scans: [{"f": "img/1773_krest_marina_tomeckova.jpg", "t": "Křest dcery Mariny 1773"}, {"f": "img/1776_krest_jan_tomecek.jpg", "t": "Křest syna Jana 1776"}], name: "Kateřina Tomečková", line: "pacik", cert: "M",
      b: { date: "?", year: 1748, approx: true }, notes: ["Rodné příjmení neznámé; sňatek s Josefem Tomečkem (cca 1770–72) zatím nečten."] },
    { id: "martinFo", scans: [{"f": "img/1774_snatek_martin_fojtik.jpg", "t": "Sňatek 23. 1. 1774"}], name: "Martin Fojtík", line: "pacik", cert: "M",
      b: { date: "?", year: 1750, approx: true }, occ: "sedlák v Nedašově Lhotě",
      marriage: "23. 1. 1774, Lhota č. 39 – s Rosinou Fojtíkovou",
      notes: ["Syn Jiřího Fojtíka. Sňatek: „Hon. adol. Martinus filius Georgii Fojtík cum hon. virgine Rosina filia † Bartholomei Fojtík, ambo Chota“; svědci Václav Lukšík (?) a Jura Birlog (?)."],
      sources: ["Brumov 4012 img 185"] },
    { id: "rosinaFo", scans: [{"f": "img/1774_snatek_martin_fojtik.jpg", "t": "Sňatek 23. 1. 1774"}], name: "Rosina Fojtíková", maiden: "Fojtíková", line: "pacik", cert: "M",
      b: { date: "?", year: 1754, approx: true }, notes: ["Dcera † Bartoloměje Fojtíka z Nedašovy Lhoty."] },
    { id: "matous1760", scans: [{"f": "img/1760_krest_matous.jpg", "t": "Křest 6. 9. 1760"}, {"f": "img/1784_snatek_matous.jpg", "t": "Sňatek 1784 – „filius defuncti Tobiae Fojtik“"}], name: "Matouš Pacík (Fojtík)", line: "pacik", cert: "M",
      notes: ["Další sestra: Kateřina (pokř. 12. 11. 1757, Nedašov).", "Sourozenci: Anna (pokř. 2. 8. 1763) a Tobiáš (pokř. 19. 11. 1766)."],
      b: { date: "6. 9. 1760 (křest)", year: 1760, place: "Nedašova Lhota" },
      father: "tobias", mother: "katerinaX", occ: "tkadlec, Nedašova Lhota č. 5",
      marriage: "1784 – s Marinou Markovou („Mathaeus filius defuncti Tobiae Fojtik“)",
      sources: ["MZA Brumov sign. 4012, img 6 a 200"] },
    { id: "marinaM", scans: [{"f": "img/1761_krest_marina_markova.jpg", "t": "Křest 29. 6. 1761"}, {"f": "img/1784_snatek_matous.jpg", "t": "Sňatek 1784"}], name: "Marina Pacíková", maiden: "Marková", line: "pacik", cert: "M",
      b: { date: "29. 6. 1761 (křest)", year: 1761, place: "Nedašov" }, father: "janMarek",
      sources: ["MZA 4012 img 9"] },
    { id: "janMarek", name: "Jan Marek", line: "pacik", cert: "M",
      b: { date: "?", year: 1730, approx: true, place: "Nedašov" }, d: { date: "před 1784", year: 1784, approx: true } },
    { id: "tobias", scans: [{"f": "img/1782_pozemkova_kniha_c5.jpg", "t": "Pozemková kniha 1782–1850: dům č. 5 „Tobias Pacžik, Häusler“"}, {"f": "img/1749_katastr_nedasova_lhota.jpg", "t": "Tereziánský katastr 1749 – Nedašova Lhota: žádný mlýn ani Pacík"}, {"f": "img/1757_krest_katerina_pacikova.jpg", "t": "Křest dcery Kateřiny 12. 11. 1757 – „Dobias Pazik Molitor“, Nedašov"}, {"f": "img/1766_krest_tobias_ml.jpg", "t": "Křest syna Tobiáše 19. 11. 1766"}, {"f": "img/1763_krest_anna_pacikova.jpg", "t": "Křest dcery Anny 2. 8. 1763 – „Tobias Fojtik seu Pacik“"}, {"f": "img/1779_umrti_tobias.jpg", "t": "Úmrtí 16. 4. 1779"}, {"f": "img/1760_krest_matous.jpg", "t": "Křest syna Matouše 1760 – „Tobiae Pazik“"}], name: "Tobiáš Pacík (Fojtík)", line: "pacik", cert: "M",
      b: { date: "cca 1712", year: 1712, approx: true },
      d: { date: "16. 4. 1779", year: 1779, place: "Nedašova Lhota č. 5" },
      occ: "mlynář (molitor)",
      notes: ["Tereziánský katastr 1749 (rektifikační fase) neuvádí v Nedašově Lhotě ani v Nedašově žádný mlýn ani Pacíka – mlýn byl nejspíš vrchnostenský (pronajímaný), nebo vznikl až po 1749. Ve Lhotě jsou ale držitelé Mikuláš a Martin Fojtík, v Nedašově Jura Fojtík. Pozemková kniha Nedašovy Lhoty (1782–1850) zapisuje dům č. 5 na „Tobias Pacžik, Häusler“ (otec, nebo syn *1766).", "Další dcera Kateřina pokř. 12. 11. 1757 („Dobias Pazik Molitor, Catharina uxor Nedašovio“); v roce 1757 tedy rodina žila v Nedašově. Tobiáš byl 1. 9. 1757 i kmotrem.", "Rodiče zatím nelze zjistit: brumovské matriky let 1706–1722 a 1727–1754 se nedochovaly (jen opisy vybraných let). V letech 1713–1757 je v Nedašově Lhotě („Zhota“) a Nedašově početný rod Fojtíků (Fogtík) – hypotéza: Tobiáš pochází od nich a „Pacík“ je jméno mlýna či usedlosti. Cesta dál vede přes pozemkové knihy a urbáře panství Brumov.", "Další doložené děti s Kateřinou: Anna (pokř. 2. 8. 1763, otec zapsán „Fojtik seu Pacik“ – tj. Fojtík neboli Pacík) a Tobiáš ml. (pokř. 19. 11. 1766).", "Nejstarší doložený předek po meči. Zemřel ve věku 67 let.", "V matrikách psán Pazik / Pačík i Fojtík – rod Pacíků se v 18. století psal Fojtík.", "Manželka Kateřina (žila 1779)."],
      sources: ["MZA Brumov sign. 4012, img 262"] },
    { id: "katerinaX", name: "Kateřina Pacíková", line: "pacik", cert: "M",
      notes: ["V úmrtích 1779–1787 není – zemřela až po roce 1787. Dcera Kateřina pokřtěna 12. 11. 1757.", "V roce 1755 třikrát kmotrou jako „Catharina Pagiczka / Pacziczka, Nedassov“ – tedy už vdaná Pacíková; rodné příjmení neznámé (sňatek spadá do mezery v matrikách 1727–1754)."],
      b: { date: "?", year: 1720, approx: true } },

    // ── Matůšů ─────────────────────────────────────────
    { id: "josefM", scans: [{"f": "img/1875_snatek_josef_matusu.jpg", "t": "1. sňatek 12. 1. 1875"}], cause: "rakovina žaludku", name: "Josef Matůšů", line: "matusu", cert: "M",
      b: { date: "17. 3. 1851", year: 1851, place: "Nedašov č. 69" },
      d: { date: "25. 8. 1900", year: 1900, place: "Nedašov č. 64" },
      father: "jiri1813", mother: "annaH", occ: "sedlák / domkář",
      marriage: "1) 12. 1. 1875 s Anežkou Markovou; 2) 10. 2. 1885 s Mariannou Novákovou",
      notes: ["Zemřel na rakovinu žaludku."] },
    { id: "mariannaN", name: "Marianna Matůšů", maiden: "Nováková", line: "matusu", cert: "M",
      b: { date: "29. 9. 1865", year: 1865, place: "Nedašov č. 88" }, father: "vaclavN", mother: "katerinaV" },
    { id: "jiri1813", scans: [{"f": "img/1813_krest_jiri_matusu.jpg", "t": "Křest 19. 8. 1813"}, {"f": "img/1834_snatek_jiri_matusu.jpg", "t": "Sňatek 1834/35"}], name: "Jiří Matůšů", line: "matusu", cert: "M",
      b: { date: "19. 8. 1813", year: 1813, place: "Nedašov č. 67" }, father: "jiri1782", mother: "barboraS",
      occ: "sedlák", marriage: "1834/35 – s Annou Holbovou" },
    { id: "annaH", scans: [{"f": "img/1812_krest_anna_holbova.jpg", "t": "Křest 10. 5. 1812"}, {"f": "img/1834_snatek_jiri_matusu.jpg", "t": "Sňatek 1834/35"}], name: "Anna Matůšů", maiden: "Holbová", line: "matusu", cert: "M",
      father: "josefHo", mother: "marinaFj",
      b: { date: "10. 5. 1812", year: 1812, place: "Nedašov č. 64" },
      notes: ["Dcera Josefa Holby, kováře (později sedláka), a Mariny Fojtíkové (dcery Jiřího Fojtíka)."] },
    { id: "vaclavN", scans: [{"f": "img/1818_krest_vaclav_novak.jpg", "t": "Křest 21. 9. 1818"}, {"f": "img/1842_snatek_novak.jpg", "t": "Sňatek 3. 2. 1842"}], name: "Václav Novák", line: "matusu", cert: "M",
      father: "martinNo", mother: "annaBi",
      b: { date: "21. 9. 1818", year: 1818, place: "Nedašov č. 45" }, occ: "podsedník",
      marriage: "3. 2. 1842 – s Kateřinou Vaculíkovou",
      notes: ["Sestra Marianna *17. 8. 1824 (4474 img 8). Příjmení matky čtené v roce 1842 jako „Belej“ je ve skutečnosti Birlog.", "Syn Martina Nováka, čtvrtláníka, a Anny roz. Belej(?)."] },
    { id: "katerinaV", scans: [{"f": "img/1842_snatek_novak.jpg", "t": "Sňatek 3. 2. 1842"}], name: "Kateřina Nováková", maiden: "Vaculíková", line: "matusu", cert: "M",
      b: { date: "cca 1824", year: 1824, approx: true, place: "Nedašov č. 88" },
      notes: ["Dcera Josefa Vaculíka, čtvrtláníka v Nedašově č. 88, a Ludmily(?) roz. Kopečné(?)."] },
    { id: "jiri1782", scans: [{"f": "img/1773_snatek_matusu_suranova.jpg", "t": "Sňatek rodičů 31. 1. 1773"}, {"f": "img/1780_krest_marina_matusu.jpg", "t": "Křest sestry Mariny 1780"}, {"f": "img/1778_krest_matous_matusu.jpg", "t": "Křest bratra Matouše 1778"}, {"f": "img/1782_krest_jiri_matusu.jpg", "t": "Křest 31. 3. 1782"}, {"f": "img/1802_snatek_jiri_matusu.jpg", "t": "Sňatek 25. 1. 1802"}], name: "Jiří Matůšů st.", line: "matusu", cert: "M",
      father: "jiriMo", mother: "marinaSu",
      b: { date: "31. 3. 1782 (křest)", year: 1782, place: "Nedašov č. 67" },
      occ: "sedlák", marriage: "25. 1. 1802 – s Barborou Šaurkovou(?) z Bylnice",
      notes: ["Bratr Martin (*cca 1784) se 27. 5. 1810 ženil jako syn † Jiřího Matůšů, sedláka (4023 img 110).", "Rodiče: Jiří Matůšů, sedlák, a Marina (Nedašov č. 67)."] },
    { id: "barboraS", scans: [{"f": "img/1779_krest_barbora_saurkova_K.jpg", "t": "Kandidát: křest 17. 9. 1779 Bylnice"}, {"f": "img/1802_snatek_jiri_matusu.jpg", "t": "Sňatek 25. 1. 1802"}], name: "Barbora Matůšů", maiden: "Šaurková (?)", line: "matusu", cert: "M",
      b: { date: "cca 1782", year: 1782, approx: true, place: "Bylnice" },
      notes: ["Dcera Mikuláše Šaurka, sedláka v Bylnici (sňatek 1802: 20 let). Kandidát na křest: 17. 9. 1779 Bylnice, Barbara dcera Mikuláše Š(a)urka a Kateřiny (4012 img 116) – věk o 2 roky nesedí.", "Dcera Mikuláše Šaurka(?), sedláka v Bylnici."] },

    { id: "jiriMo", scans: [{"f": "img/1773_snatek_matusu_suranova.jpg", "t": "Sňatek 31. 1. 1773"}, {"f": "img/1810_snatek_martin_matusu.jpg", "t": "Sňatek syna Martina 1810 – otec už zemřelý"}], name: "Jiří Matůšů", line: "matusu", cert: "M",
      b: { date: "cca 1748", year: 1748, approx: true, place: "Nedašov" }, d: { date: "před 27. 5. 1810", year: 1809, approx: true },
      occ: "sedlák, Nedašov č. 67", marriage: "31. 1. 1773, Nedašov – s Marinou Šuranovou",
      notes: ["Syn † Václava Matůšů (zemřel před 1773). Sňatek: „honestus adol. georgius filius † Wenceslai Matussuj, cum honesta Virg. Marina filia Josephi Ssuran Num. 79. ambo Nedascho.“ Svědci Martin Kolínek, Bartoš Birlog (?)."],
      sources: ["Brumov 4012 img 183", "O 4023 img 110"] },
    { id: "marinaSu", scans: [{"f": "img/1773_snatek_matusu_suranova.jpg", "t": "Sňatek 31. 1. 1773"}], name: "Marina Matůšů", maiden: "Šuranová", line: "matusu", cert: "M",
      b: { date: "cca 1752", year: 1752, approx: true, place: "Nedašov č. 79" },
      notes: ["Dcera Josefa Šurana z Nedašova č. 79."], sources: ["Brumov 4012 img 183"] },
    { id: "josefHo", scans: [{"f": "img/1794_snatek_holba_fojtikova.jpg", "t": "Sňatek 26. 1. 1794"}], name: "Josef Holba", line: "matusu", cert: "M",
      b: { date: "cca 1769", year: 1769, approx: true, place: "Nedašov" }, occ: "kovář, později sedlák, Nedašov č. 64",
      marriage: "26. 1. 1794, Nedašov č. 64 – s Marinou Fojtíkovou (on 25, ona 18); svědci Johann Holba a Mathis Jakubík",
      notes: ["Syn Matěje (Mathes) Holby, kováře v Nedašově."], sources: ["O 4023 img 104"] },
    { id: "marinaFj", scans: [{"f": "img/1794_snatek_holba_fojtikova.jpg", "t": "Sňatek 26. 1. 1794"}], name: "Marina Holbová", maiden: "Fojtíková", line: "matusu", cert: "M",
      b: { date: "cca 1776", year: 1776, approx: true, place: "Nedašov" },
      notes: ["Dcera Jiřího Fojtíka, sedláka v Nedašově."], sources: ["O 4023 img 104"] },
    { id: "martinNo", scans: [{"f": "img/1818_krest_vaclav_novak.jpg", "t": "Křest syna Václava 1818"}], name: "Martin Novák", line: "matusu", cert: "M",
      b: { date: "?", year: 1785, approx: true }, occ: "sedlák (čtvrtláník), Nedašov č. 45",
      notes: ["Sňatek s Annou Birlogovou zatím nenalezen (není v 4023 v letech 1805–1817)."] },
    { id: "annaBi", scans: [{"f": "img/1818_krest_vaclav_novak.jpg", "t": "Křest syna Václava 1818"}], name: "Anna Nováková", maiden: "Birlog (Bírlogová)", line: "matusu", cert: "M",
      b: { date: "?", year: 1790, approx: true }, notes: ["Dcera † Jiřího Birloga, domkáře v Nedašově."] },
    // ── Struž ──────────────────────────────────────────
    { id: "margareta", cause: "mrtvice", name: "Margareta Pacíková", maiden: "Stružová", line: "struz", cert: "D",
      b: { date: "20. 12. 1937", year: 1937, place: "pravděpodobně Opava" },
      d: { date: "28. 11. 2016", year: 2016, place: "Ostrava" },
      father: "arnost", mother: "marieJ",
      notes: ["Pohřbena v Chuchelné.", "Sourozenci: Anežka Manová (*22. 1. 1951 Opava), Erich, sestra zemřelá jako dítě za války."] },
    { id: "arnost", scans: [{"f": "img/1937_snatek_struz_jirikova.jpg", "t": "Sňatek 25. 1. 1937, Chuchelná (ST VIII 198)"}, {"f": "img/1907_narozeni_arnost.jpg", "t": "Narození 3. 12. 1907"}], name: "Arnošt Struž (Ernst Strusch)", line: "struz", cert: "M",
      b: { date: "3. 12. 1907", year: 1907, place: "Chuchelná" },
      d: { date: "18. 10. 1999", year: 1999, place: "Chuchelná č. 160" },
      marriage: "25. 1. 1937, Chuchelná (kostel) – s Marií Jiříkovou",
      father: "karlS", mother: "antonia", occ: "strojní zámečník",
      notes: ["Bratr Paul Strusch *17. 7. 1894 Chuchelná, mušketýr, padl 21. 3. 1916 v Bois de Malancourt (Verdun).", "V soupisu majitelů domů 1950 vlastník Chuchelné č. 105.", "Za okupace člen Freikorpsu a SA; 1940 povolán do wehrmachtu, v únoru 1941 propuštěn a zaměstnán v rafinérii v Heydebrecku (Horní Slezsko). Po válce odsouzen Mimořádným lidovým soudem v Opavě k 1 roku vězení, majetek z velké části zkonfiskován (Hultschiner Soldaten).", "Sňatek 25. 1. 1937 v kostele v Chuchelné (oddával P. Jan Valerian): zámečník v čs. továrně na tabák v Chuchelné, bytem Chuchelná č. 46; svědci Viktor Komárek (domkář č. 115) a Metoděj Mikler (domkář č. 27).", "1950 bydlel Chuchelná č. 105.", "Voják 1940–41 (Hultschiner Soldaten); po válce odsouzen lidovým soudem k 1 roku a konfiskaci části majetku."],
      sources: ["Standesamt Kuchelna N 1907 Nr. 56 – ZA Opava"] },
    { id: "karlS", scans: [{"f": "img/1916_umrti_paul_strusch.jpg", "t": "Padlý syn Paul 1916 – „Amtsdiener Karl Strusch, verstorben“ (Z 1916 Nr. 30)"}, {"f": "img/1907_narozeni_arnost.jpg", "t": "Narození syna Arnošta 1907"}, {"f": "img/1909_umrti_marie_strusch_kussin.jpg", "t": "Úmrtí Marie Strusch roz. Kussin 1909 – ohlásil Karl"}], name: "Karl Strusch (Karel Struž)", line: "struz", cert: "M",
      b: { date: "cca 1870–1874", year: 1871, approx: true },
      d: { date: "před 20. 5. 1916 (nejspíš 1915)", year: 1915, approx: true, place: "Chuchelná" },
      occ: "panský (zámecký) zahradník v Chuchelné, později úřední sluha",
      marriage: "před 7/1894 – s Antonií Komárkovou",
      notes: ["Doložen v matrikách jako otec Arnošta (*1907) a Paula (*17. 7. 1894, padl 21. 3. 1916 u Verdunu); manželka Antonie roz. Komárková.", "1909 „Schloßgärtner“ (zámecký zahradník), 1916 „Amtsdiener“ (úřední sluha). Zemřel před 20. 5. 1916 – nejspíš v lednu–září 1915 (zápisy Z 1915 Nr. 1–25 nejsou digitalizované).", "Sňatek s Antonií před červencem 1894 – v Chuchelné 1895–1907 není, hledá se v letech 1888–1894. Narození není v Chuchelné X/1874–1880 ani v křtech Krzanowic 1832–1870 → nejspíš 1870–IX/1874.", "RODIČE zatím neověřeni. Nejsilnější kandidát (K): Johann Strusch, domkář, × Marie roz. Kussin (sňatek 19. 1. 1858) – Karl osobně ohlásil 22. 11. 1909 úmrtí Marie Strusch roz. Kussin (73 let) a jméno má po jejím otci Karlu Kussinovi. Dřívější kandidáti: Anton Strusch (*1833) a Jakob Strusch (†1917), oba synové Mikuláše Strusche a Barbory Saitzek."],
      sources: ["Standesamt Kuchelna N 1907 Nr. 56; Z 1909 Nr. 24; Z 1916 Nr. 30 – ZA Opava", "O 1937 Chuchelná (ST VIII 198)"] },
    { id: "antonia", scans: [{"f": "img/1916_umrti_paul_strusch.jpg", "t": "Padlý syn Paul 1916 (Z 1916 Nr. 30)"}, {"f": "img/1907_narozeni_arnost.jpg", "t": "Narození syna Arnošta 1907"}], name: "Antonie Strusch", maiden: "Komárková (Komarek)", line: "struz", cert: "M",
      b: { date: "?", year: 1882, approx: true }, notes: ["Ještě žila v květnu 1916 (zápis o padlém synu Paulovi).", "Do roku 1880 se v civilních matrikách Chuchelné nenarodila; Komárkové v Chuchelné/Strahovicích: Carl × Helena Mitrenga, Adolph × Johanna Juretzka, Joseph × Marika Jaschek (Strandorf).", "Možní rodiče: Komárkové oddaní v Chuchelné 1880 (Franz, Anton) – neověřeno."] },

    // ── Jiřík / Opoloný ────────────────────────────────
    { id: "marieJ", scans: [{"f": "img/1937_snatek_struz_jirikova.jpg", "t": "Sňatek 25. 1. 1937, Chuchelná (ST VIII 198)"}, {"f": "img/1914_narozeni_marie_jirikova.jpg", "t": "Narození 9. 9. 1914"}], cause: "leukémie", name: "Marie Stružová", maiden: "Jiříková (Irzik)", line: "jirik", cert: "M",
      b: { date: "9. 9. 1914", year: 1914, place: "Chuchelná" },
      d: { date: "cca 1978", year: 1978, approx: true, place: "Opava" },
      father: "rudolfI", mother: "marieO",
      notes: ["Při sňatku 1937 dělnice v čs. továrně na tabák v Chuchelné, bytem Chuchelná č. 24 (?).", "Nejstarší z 9 dětí (paměti sestry Antonie Jiříkové): Jiří, Ludvina, Helena, Anna, Antonie, Adolf 1925, Rudolf 1926, Robert 1928.", "Švadlena, od 17 let v tabákovně."],
      sources: ["Standesamt Kuchelna N 1914 Nr. 34"] },
    { id: "rudolfI", scans: [{"f": "img/1882_narozeni_rudolf_irzik.jpg", "t": "Narození 17. 4. 1882"}, {"f": "img/1910_snatek_irzik_opolony.jpg", "t": "Sňatek 24. 1. 1910"}], name: "Rudolf Jiřík (Irzik)", line: "jirik", cert: "M",
      b: { date: "17. 4. 1882", year: 1882, place: "Bolatice" },
      father: "franzI", mother: "marieH", occ: "zedník, později výrobce cementového zboží",
      marriage: "24. 1. 1910, Chuchelná – s Marií Opolony",
      notes: ["1937 uveden jako malorolník a obchodník v Chuchelné; ve 30. letech člen místní školské rady; 1950 majitel domu č. 75.", "Chuchelná č. 75; velitel hasičů, člen místní školní rady."],
      sources: ["Standesamt Bolatice N 1882 Nr. 29; Kuchelna O 1910 Nr. 2"] },
    { id: "marieO", scans: [{"f": "img/1885_narozeni_marie_opolony.jpg", "t": "Narození 30. 6. 1885"}, {"f": "img/1910_snatek_irzik_opolony.jpg", "t": "Sňatek 24. 1. 1910"}], name: "Marie Jiříková", maiden: "Opolony (Opoloná)", line: "opolony", cert: "M",
      b: { date: "30. 6. 1885", year: 1885, place: "Chuchelná" },
      father: "antonO", mother: "rosalie",
      notes: ["Bratr pravděpodobně kovář Adolf Opoloný (starosta 1931)."], sources: ["Kuchelna N 1885 Nr. 18"] },
    { id: "franzI", scans: [{"f": "img/1882_narozeni_rudolf_irzik.jpg", "t": "Narození syna Rudolfa 1882"}], name: "Franz Irzik", line: "jirik", cert: "M",
      b: { date: "?", year: 1850, approx: true }, occ: "domkář, 1910 řeznický mistr v Bolaticích",
      notes: ["Sňatek s Marií Herudek není v civilních matrikách Bolatic 1874–1881 – uzavřen dříve, jen církevně.", "Kandidát na rodinu: Franz Irzik × Carolina Scholtis (syn Valentina Irzika z Henneberku), Bolatice 1844 – neověřeno."] },
    { id: "marieH", scans: [{"f": "img/1882_narozeni_rudolf_irzik.jpg", "t": "Narození syna Rudolfa 1882"}], name: "Marie Irzik", maiden: "Herudek", line: "jirik", cert: "M",
      b: { date: "?", year: 1852, approx: true }, d: { date: "před 1910", year: 1910, approx: true } },
    { id: "antonO", scans: [{"f": "img/1923_umrti_antonin_opolony.jpg", "t": "Úmrtí 9. 2. 1923 (Z 1923 Nr. 2)"}, {"f": "img/1878_narozeni_adolph_opolony.jpg", "t": "Narození syna Adolpha 9. 4. 1878"}, {"f": "img/1913_umrti_rosalie_opolony.jpg", "t": "Úmrtí manželky Rosalie 1913"}, {"f": "img/1885_narozeni_marie_opolony.jpg", "t": "Narození dcery Marie 1885"}], name: "Anton Opolony", line: "opolony", cert: "M",
      cause: "zešlost věkem",
      d: { date: "9. 2. 1923", year: 1923, place: "Chuchelná č. 70" },
      b: { date: "15. 1. 1841", year: 1841, place: "Ehrenfeld, okr. Kosel (Horní Slezsko, Prusko)" }, occ: "kovářský mistr v Chuchelné",
      notes: ["Úmrtí 9. 2. 1923 v Chuchelné č. 70 jako výměnkář, vdovec; pohřben 13. 2. 1923 (P. Jan Valerian). V roce 1913 se uvádí jako Gärtnerauszügler (zahradník na výměnku). Do Chuchelné se přistěhoval z Ehrenfeldu u Kozlí (Kosel).", "Kovářský mistr (Schmiedemeister) v Chuchelné; syn Adolph *9. 4. 1878 (pravděpodobně pozdější starosta). Ve farních matrikách Krzanowic 1832–1870 se Opoloní nevyskytují – Anton se zřejmě přistěhoval.", "Sňatek není v Chuchelné 1874–1884 – pravděpodobně před 1874 ve farnosti Krzanowice (PL)."] },
    { id: "rosalie", scans: [{"f": "img/1878_narozeni_adolph_opolony.jpg", "t": "Narození syna Adolpha 9. 4. 1878"}, {"f": "img/1913_umrti_rosalie_opolony.jpg", "t": "Úmrtí 21. 7. 1913 (Z 1913 Nr. 15)"}, {"f": "img/1885_narozeni_marie_opolony.jpg", "t": "Narození dcery Marie 1885"}], name: "Rosalie Opolony", maiden: "Czienskowski / Cienskowski", line: "opolony", cert: "M",
      father: "janCz", mother: "luziaB",
      d: { date: "21. 7. 1913", year: 1913, place: "Chuchelná" },
      b: { date: "cca 1845", year: 1845, approx: true, place: "Schonowitz (Horní Slezsko)" }, notes: ["Úmrtí 21. 7. 1913 ve 14:30, 68 let, „geboren zu Schonowitz“; dcera zahradníka Johanna Czienskowského a Luzie roz. Blana (?), oba zemřelí, naposledy v Schonowitz. Oznámil manžel Anton Opolony.", "Rodné příjmení čteno nejistě („Czeikowsky“ / „Czilakowsky“)."] },
    { id: "janCz", scans: [{"f": "img/1913_umrti_rosalie_opolony.jpg", "t": "Úmrtí dcery Rosalie 1913"}], name: "Johann Czienskowski", line: "opolony", cert: "M",
      b: { date: "?", year: 1815, approx: true }, occ: "zahradník (Gärtner) v Schonowitz", notes: ["Zemřel před 1913."] },
    { id: "luziaB", scans: [{"f": "img/1913_umrti_rosalie_opolony.jpg", "t": "Úmrtí dcery Rosalie 1913"}], name: "Luzia Czienskowski", maiden: "Blana (?)", line: "opolony", cert: "M",
      b: { date: "?", year: 1818, approx: true }, notes: ["Zemřela před 1913, naposledy v Schonowitz."] }
  ]
};

// ── Origin map and historical context ─────────────────────────────
window.RODOKMEN.places = [
  { name: "Ostrava", lat: 49.835, lon: 18.29, hub: true, note: "Místo, kde se větve setkaly" },
  { name: "Kežmarok", dy: 6, lat: 49.135, lon: 20.43, line: "vesely", note: "Narození Svatoně Veselého 1933" },
  { name: "Věrovany", anchor: "start", dy: 4, lat: 49.46, lon: 17.29, line: "vesely", note: "Rod Plachý (Anna *1907)" },
  { name: "Wieliczka", anchor: "end", dy: 16, lat: 49.987, lon: 20.065, line: "woron", note: "sňatek Woroňových 1896", small: true },
  { name: "Opava", anchor: "end", dy: 4, lat: 49.94, lon: 17.90, line: "struz", note: "Stružovi kolem 1937", small: true },
  { name: "Uherský Brod", dy: 4, lat: 49.025, lon: 17.65, line: "vesely", note: "Veselí kolem 1940", small: true },
  { name: "Lednica Dolna", dy: -22, lat: 49.985, lon: 20.03, line: "woron", note: "Rod Woroń, Ondřej *1869 (?)" },
  { name: "Rajbrot", dy: 6, lat: 49.80, lon: 20.42, line: "woron", note: "Rod Włudyka od 1730. let" },
  { name: "Zagórzany (Gdów)", dy: 6, lat: 49.93, lon: 20.21, line: "chmielek", note: "Rod Chmielek (Stanislav)" },
  { name: "Tarnów", anchor: "end", dy: -24, lat: 50.01, lon: 20.99, line: "chmielek", note: "Rod Dydowicz (Helena)" },
  { name: "Nedašova Lhota", dy: -22, lat: 49.135, lon: 18.09, line: "pacik", note: "Rod Pacík / Fojtík od 1712" },
  { name: "Nedašov", dy: 8, lat: 49.105, lon: 18.06, line: "matusu", note: "Rod Matůšů, Novák, Holba" },
  { name: "Chuchelná", dy: -24, lat: 50.00, lon: 18.03, line: "struz", note: "Rody Strusch, Opolony, Jiřík" },
  { name: "Bolatice", anchor: "start", dy: 2, lat: 49.95, lon: 18.08, line: "jirik", note: "Rudolf Irzik *1882" }
];
window.RODOKMEN.story = [
  { line: "pacik", title: "Valašsko pod Bílými Karpaty – Pacíci a Matůšů",
    text: [
      "Nedašov a Nedašova Lhota leží na moravsko-slovenském pomezí pod Bílými Karpaty a patřily k panství Brumov. Nejstarší doložený předek, mlynář Tobiáš Pacík (*cca 1712, †1779), žil v domě č. 5, kde rod přebýval přes 150 let.",
      "V matrikách 18. století se stejná rodina psala jednou „Pacík“, jindy „Fojtík“ – příjmení se v té době teprve ustalovala. Zápisy jsou latinsky, v 19. století německy a od 70. let česky.",
      "Předkové byli domkáři, podsedníci a tkalci – drobní venkované bez větší půdy. Dědeček Rudolf (*1936) odešel jako mnoho Valachů za prací do průmyslové Ostravy."
    ] },
  { line: "struz", title: "Hlučínsko – Struž, Jiřík a Opoloný",
    text: [
      "Chuchelná a Bolatice leží na Hlučínsku. Po slezských válkách v roce 1742 připadlo Prusku, takže zdejší lidé byli 178 let pruskými (později německými) občany, i když mluvili moravským nářečím „po našymu“.",
      "Proto jsou jejich matriky od roku 1874 německé civilní (Standesamt Kuchelna) a jména se psala německy: Ernst Strusch, Rudolf Irzik, Marie Opolony.",
      "V roce 1920 bylo Hlučínsko připojeno k Československu, v roce 1938 k Německu a v roce 1945 znovu k ČSR. Muži jako Arnošt Struž proto za 2. světové války sloužili v německé armádě a po válce byli souzeni lidovými soudy."
    ] },
  { line: "woron", title: "Halič – Woroň, Włudyka, Chmielek a Dydowicz",
    text: [
      "Halič (polsky Galicja) byla v letech 1772–1918 korunní zemí Rakouska-Uherska – zhruba dnešní jižní Polsko a západní Ukrajina. Na přelomu 19. a 20. století patřila k nejchudším oblastem Evropy („galicyjska bieda“).",
      "Tisíce lidí proto odcházely za prací do ostravských dolů – byly ve stejné monarchii, takže se dalo volně stěhovat. Přesně tak přišli Ondřej Woroń z Lednice u Wieliczky, Markéta Włudyka z Rajbrotu (rod Włudyků tam žil už v 18. století), Stanislav Chmielek ze Zagórzan a Helena Dydowicz od Tarnova.",
      "Usadili se v hornické Polské Ostravě (od roku 1919 Slezská Ostrava), kde se jim v roce 1903 narodili Ludvík a Honorata – rodiče babičky Marty."
    ] },
  { line: "vesely", title: "Spiš – Veselí a Plaší",
    text: [
      "Po vzniku Československa v roce 1918 odcházely na Slovensko tisíce Čechů – úředníci, železničáři, četníci, učitelé i řemeslníci. Mezi nimi Karel Veselý (*1904 u Českých Budějovic), který v listopadu 1922 přišel z Plzně do Kežmarku a pracoval jako úředník tamní nemocenské pojišťovny.",
      "Kežmarok byl tehdy převážně německé a maďarské město – sčítací arch z roku 1930 je vyplněný německy. Karel bydlel v podnájmu na Hlavní ulici, v letech 1935–1937 seděl v městském zastupitelstvu za sociální demokraty a dělal jednatele Klubu československých turistů.",
      "Anna Plachá (*1907) pocházela z Věrovan na Hané. Do Kežmarku ji přivedla starší sestra Terezie, provdaná za řezníka Methoda Krejsu, kterému Anna dělala pokladní. S Karlem se vzali mezi lety 1931 a 1933 a v září 1933 se jim narodil Svatoň.",
      "Po vzniku Slovenského státu v roce 1939 museli Češi ve státní službě většinou odejít do českých zemí – rodina Veselých se tak přestěhovala do Uherského Brodu, jak babička Marta mnohokrát vyprávěla."
    ] }
];
window.RODOKMEN.timeline = [
  { y: 1712, t: "Narozen Tobiáš Pacík (Fojtík), nejstarší doložený předek" },
  { y: 1759, t: "V Rajbrotu se berou Jan Włodyka a Konstancie Kanownik" },
  { y: 1805, t: "V Rajbrotu pokřtěn František Włudyka, praděd babičky Marty" },
  { y: 1742, t: "Hlučínsko připadá Prusku" },
  { y: 1772, t: "Vzniká Halič jako součást habsburské monarchie" },
  { y: 1874, t: "V Prusku začínají civilní matriky (Standesamt)" },
  { y: 1896, t: "Woroňové a Chmielkové odcházejí z Haliče na Ostravsko (cca)" },
  { y: 1903, t: "V Polské Ostravě se rodí Ludvík Woroň a Honorata Chmielková" },
  { y: 1918, t: "Vzniká Československo, konec Haliče" },
  { y: 1920, t: "Hlučínsko připojeno k ČSR" },
  { y: 1922, t: "Karel Veselý přichází z Plzně do Kežmarku" },
  { y: 1930, t: "Sčítání lidu: Karel i Anna Plachá žijí v Kežmarku, zatím svobodní" },
  { y: 1933, t: "Svatoň Veselý se rodí v Kežmarku" },
  { y: 1935, t: "Karel Veselý městským zastupitelem v Kežmarku" },
  { y: 1938, t: "Hlučínsko připojeno k Německu" },
  { y: 1940, t: "Veselí odcházejí z Kežmarku do Uherského Brodu" },
  { y: 1945, t: "Konec války, Hlučínsko znovu v ČSR" },
  { y: 1957, t: "Svatba Svatoně Veselého a Marty Woroňové ve Slezské Ostravě" },
  { y: 1985, t: "Svatba Radima Veselého a Jany Pacíkové" },
  { y: 1986, t: "Narozen Matěj Veselý" }
];

// Documented migrations, drawn along period railway lines where the exact route is unknown.
// kind: "doc" = move documented in records, "rail" = probable route by train, "hyp" = hypothesis
window.RODOKMEN.moves = [
  { line: "matusu", kind: "doc", who: "Anna Matůšů", when: "1916", note: "sňatkem z Nedašova do Nedašovy Lhoty č. 5",
    path: [[49.105, 18.06], [49.135, 18.09]] },
  { line: "pacik", kind: "doc", who: "Rudolf Pacík (*1936)", when: "cca 1960", note: "z Nedašovy Lhoty za prací do Ostravy",
    path: [[49.135, 18.09], [49.22, 18.0], [49.455, 17.95], [49.60, 18.14], [49.835, 18.29]], railVia: "Vlára – Vsetín – Valašské Meziříčí" },
  { line: "jirik", kind: "doc", who: "Rudolf Irzik", when: "1910", note: "sňatkem z Bolatic do Chuchelné",
    path: [[49.95, 18.08], [50.00, 18.03]] },
  { line: "struz", kind: "doc", who: "Arnošt a Marie Stružovi", when: "1937", note: "dcera Margareta se narodila pravděpodobně v Opavě",
    path: [[50.00, 18.03], [49.94, 17.90]] },
  { line: "struz", kind: "doc", who: "Margareta Stružová", when: "cca 1960", note: "z Opavy do Ostravy, sňatek s Rudolfem Pacíkem",
    path: [[49.94, 17.90], [49.90, 18.10], [49.835, 18.29]] },
  { line: "woron", kind: "doc", who: "Markéta Włudyka", when: "1896", note: "z Rajbrotu na Ostravsko; sňatek s Ondřejem Woroněm 24. 8. 1896 – v Rajbrotu ani ve Wieliczce není, nejspíš byl až v Ostravě",
    path: [[49.80, 20.42], [49.97, 20.43], [49.987, 20.065]] },
  { line: "woron", kind: "doc", who: "Ondřej Woroń", when: "1896", note: "z Lednice Dolní (předměstí Wieliczky)",
    path: [[49.985, 20.03], [49.987, 20.065]] },
  { line: "woron", kind: "rail", who: "Ondřej a Markéta Woroňovi", when: "1896–1903", note: "z Wieliczky do Polské Ostravy; trasa vlakem Kraków – Oświęcim – Bohumín je pravděpodobná, nedoložená",
    path: [[49.987, 20.065], [50.06, 19.94], [50.04, 19.22], [49.95, 18.75], [49.90, 18.36], [49.835, 18.29]] },
  { line: "chmielek", kind: "rail", who: "Stanislav Chmielek", when: "před 1903", note: "ze Zagórzan do Polské Ostravy; trasa přes Kraków pravděpodobná",
    path: [[49.93, 20.21], [50.06, 19.94], [50.04, 19.22], [49.95, 18.75], [49.90, 18.36], [49.835, 18.29]] },
  { line: "chmielek", kind: "hyp", who: "Helena Dydowicz", when: "před 1903", note: "z Rudna u Tarnova do Polské Ostravy; kudy a kdy šla, zatím nevíme",
    path: [[50.01, 20.99], [50.06, 19.94]] },
  { line: "vesely", kind: "doc", who: "Karel Veselý", when: "1922", note: "z Plzně (narozen 1904 u Českých Budějovic) do Kežmarku; vlakem přes Přerov – Žilinu – Poprad",
    path: [[49.40, 16.95], [49.455, 17.45], [49.60, 18.14], [49.22, 18.74], [49.06, 20.30], [49.135, 20.43]], fromOffMap: "z Plzně" },
  { line: "vesely", kind: "doc", who: "Anna Plachá", when: "1930", note: "z Věrovan za sestrou Terezií Krejsovou do Kežmarku",
    path: [[49.46, 17.29], [49.455, 17.45], [49.60, 18.14], [49.22, 18.74], [49.06, 20.30], [49.135, 20.43]] },
  { line: "vesely", kind: "doc", who: "Veselí se Svatoněm", when: "cca 1939–1940", note: "po vzniku Slovenského státu odchod do Uherského Brodu – potvrzeno vyprávěním babičky Marty (opakovaně)",
    path: [[49.135, 20.43], [49.06, 20.30], [49.22, 18.74], [49.025, 17.65]] },
  { line: "vesely", kind: "hyp", who: "Svatoň Veselý", when: "před 1957", note: "do Ostravy; sňatek s Martou Woroňovou 1957 ve Slezské Ostravě",
    path: [[49.025, 17.65], [49.455, 17.45], [49.60, 18.14], [49.835, 18.29]] }
];
