// Rodokmen Matěje Veselého – data (generated from RODOKMEN_stav_vyzkumu.md, update with every research iteration)
// cert: M = přečteno v matrice, D = jiný doklad, R = rodinná tradice, K = kandidát / neověřeno
window.RODOKMEN = {
  updated: "6. 10. 2026",
  root: "matej",
  lines: {
    vesely: "Veselý",
    woron: "Woroň",
    chmielek: "Chmielek",
    pacik: "Pacík",
    matusu: "Matůšů",
    struz: "Struž",
    jirik: "Jiřík",
    opolony: "Opoloný"
  },
  people: [
    { id: "matej", name: "Matěj Veselý", line: "vesely", cert: "D",
      b: { date: "15. 1. 1986", year: 1986, place: "Ostrava" },
      father: "radim", mother: "jana",
      notes: ["Výchozí osoba rodokmenu.", "Nemá sourozence."] },

    // ── Veselý ─────────────────────────────────────────
    { id: "radim", name: "Radim Veselý", line: "vesely", cert: "R",
      b: { date: "1961", year: 1961, place: "pravděpodobně Frýdek-Místek" },
      father: "svaton", mother: "marta",
      marriage: "22. 6. 1985 – s Janou Pacíkovou (údaj rodiny)",
      notes: ["Sestra Miluše Kempná, roz. Veselá (*19. 4. 1958 Ostrava-Fifejdy), manžel Rostislav Kempný, děti Rostislav a Barbora."] },
    { id: "jana", name: "Jana Veselá", maiden: "Pacíková", line: "pacik", cert: "D",
      b: { date: "23. 6. 1962", year: 1962, place: "Ostrava" },
      father: "rudolf1936", mother: "margareta",
      notes: ["Sourozenci: Rudolf Pacík (*29. 3. 1961 Ostrava, †3. 8. 2018 Ostrava, pohřben v Chuchelné), Tomáš Pacík."] },
    { id: "svaton", name: "Svatoň Veselý", line: "vesely", cert: "D",
      b: { date: "17. 9. 1933", year: 1933, place: "Kežmarok (Slovensko)" },
      d: { date: "19. 9. 2007", year: 2007, place: "FN Ostrava-Poruba" },
      father: "karelV", mother: "annaP",
      marriage: "28. 9. 1957, Slezská Ostrava (kostel sv. Josefa) – s Martou Woroňovou",
      notes: ["Rodinný hrob v Hodoňovicích.", "Sourozenci: Karel, Růženka.", "V poznámkách se objevuje Uherský Brod 1940 – význam neověřen.", "Odpis rodného listu vyžádán z Matričného úradu Kežmarok (6. 10. 2026)."] },
    { id: "karelV", name: "Karel Veselý", line: "vesely", cert: "R",
      b: { date: "cca 1903", year: 1903, approx: true },
      notes: ["Rodiče a původ zatím neznámé.", "Kandidát: Karel Veselý, předseda ONV Uherský Brod 1945 (neověřeno)."] },
    { id: "annaP", name: "Anna Veselá", maiden: "Plachá", line: "vesely", cert: "R",
      b: { date: "?", year: 1908, approx: true },
      notes: ["Údaje neznámé – čeká se na rodný zápis Svatoně z Kežmarku."] },

    // ── Woroň / Chmielek ───────────────────────────────
    { id: "marta", name: "Marta Veselá", maiden: "Woroňová", line: "woron", cert: "D",
      b: { date: "4. 12. 1939", year: 1939, place: "Ostrava" },
      father: "ludvik", mother: "honorata", alive: true,
      notes: ["Žije. Vyrůstala v Ostravě 8.", "Sestra Libuše Randulová (manžel Josef, děti Dušan a Tomáš); sourozenci Miloslava a Jaroslav zemřeli před jejím narozením."] },
    { id: "ludvik", name: "Ludvík Woroň", line: "woron", cert: "M",
      b: { date: "18. 7. 1903", year: 1903, place: "Polská (Slezská) Ostrava č. 69, Kamenec" },
      d: { date: "21. 8. 1986", year: 1986 },
      father: "andreas", mother: "margaretha",
      marriage: "9. 8. 1925 – s Honoratou Chmielkovou (poznámka v křestní matrice; oba vystoupili z církve 19. 2. 1925 – sňatek zřejmě civilní, zápis zatím nenalezen)",
      notes: ["Pokřtěn 20. 7. 1903. Rodina uváděla narození 19. 8. 1903 – matrika říká 18. 7.", "Kmotři: Tomáš(?) Woroň, horník na Hranečníku, a Josefa, jeho manželka."],
      sources: ["ř.-k. fara Slezská Ostrava, N 1902–1905 (SO VII 36), fol. 171 – ZA Opava"] },
    { id: "honorata", name: "Honorata Woroňová", maiden: "Chmielková", line: "chmielek", cert: "M",
      b: { date: "10. 9. 1903", year: 1903, place: "Polská (Slezská) Ostrava č. 17" },
      d: { date: "12. 8. 1968", year: 1968 },
      father: "stanislaus", mother: "helenaD",
      notes: ["Pokřtěna 19. 9. 1903 jako Honorata Maria.", "Poznámka v matrice: oddána 9. 8. 1925 s Ludvíkem Woroněm."],
      sources: ["ř.-k. fara Slezská Ostrava, N 1902–1905 (SO VII 36), sken 101 – ZA Opava"] },
    { id: "andreas", name: "Ondřej (Andreas) Woroń", line: "woron", cert: "M",
      b: { date: "19. 10. 1869 (?)", year: 1869, place: "Lednica Dolna, okr. Wieliczka (Halič)" },
      occ: "horník",
      marriage: "24. 8. 1896 (?) – s Markétou Wludyka",
      notes: ["Data ze sloupců křestního zápisu syna čtena nejistě.", "Rod Woroń je v Lednici Dolní doložen už kolem roku 1780 (strom FamilySearch)."],
      sources: ["SO VII 36, fol. 171"] },
    { id: "margaretha", name: "Markéta (Margaretha) Woroń", maiden: "Wludyka", line: "woron", cert: "M",
      b: { date: "17. 7. 1875 (?)", year: 1875, place: "Rajbrot, okr. Bochnia (Halič)?" },
      father: "franzW",
      notes: ["Dcera Františka Wludyky, rolníka v Rajbrotu.", "Rodinné poznámky ji chybně uváděly jako „Helenu Chmielkovou“."],
      sources: ["SO VII 36, fol. 171"] },
    { id: "franzW", name: "František (Franz) Wludyka", line: "woron", cert: "M",
      b: { date: "?", year: 1845, approx: true, place: "Rajbrot, okr. Bochnia" },
      occ: "rolník (Ackerbauer) v Rajbrotu" },
    { id: "stanislaus", name: "Stanislav (Stanislaus) Chmielek", line: "chmielek", cert: "M",
      b: { date: "7. 1. 1876 (?)", year: 1876, place: "Zagórzany, okr. Wieliczka (Halič)" },
      occ: "horník",
      marriage: "18. 9. 1903 (?) – s Helenou Dydowicz",
      sources: ["SO VII 36, sken 101"] },
    { id: "helenaD", name: "Helena Chmielková", maiden: "Dydowicz", line: "chmielek", cert: "M",
      b: { date: "1. 9. 1884 (?)", year: 1884, place: "Rudno, okr. Tarnów (Halič)?" },
      father: "tomasD",
      notes: ["Dcera Tomáše Dydowicze, domkáře v Rudně.", "Toto je „Helena Chmielková“ z rodinných poznámek – matka Honoraty."],
      sources: ["SO VII 36, sken 101"] },
    { id: "tomasD", name: "Tomáš Dydowicz", line: "chmielek", cert: "M",
      b: { date: "?", year: 1855, approx: true, place: "Rudno, okr. Tarnów" },
      occ: "domkář (Gärtler)" },

    // ── Pacík ──────────────────────────────────────────
    { id: "rudolf1936", name: "Rudolf Pacík", line: "pacik", cert: "D",
      b: { date: "5. 6. 1936", year: 1936, place: "Nedašova Lhota" },
      d: { date: "3. 5. 2013", year: 2013, place: "Ostrava" },
      father: "frantisek1892", mother: "annaM",
      marriage: "cca 1960 – s Margaretou Stružovou",
      notes: ["Pohřben v Chuchelné.", "Starší sourozenci (matrika): František *16. 11. 1916, Františka *5. 1. 1919, Jan *23. 10. 1920, Alois *7. 11. 1922; sestra Marie, provd. Halamová (Orlová).", "Narození 1936 ještě není v archivu (100letá lhůta)."] },
    { id: "frantisek1892", name: "František Pacík", line: "pacik", cert: "M",
      b: { date: "14. 7. 1892", year: 1892, place: "Nedašova Lhota č. 5" },
      d: { date: "1965 (?)", year: 1965, approx: true },
      father: "jan1861", mother: "frantiskaT",
      occ: "dělník / domkář; 1916 domobranec",
      marriage: "8. 2. 1916, Nedašov – s Annou Matůšů",
      notes: ["Verze „zemřel v USA“ vyvrácena.", "Úmrtí 1965 jen podle stromu na Geni (neověřeno)."],
      sources: ["MZA Brno, N 4482 str. 49; O 4486 str. 67"] },
    { id: "annaM", name: "Anna Pacíková", maiden: "Matůšů", line: "matusu", cert: "M",
      b: { date: "16. 4. 1894", year: 1894, place: "Nedašov č. 64" },
      d: { date: "1968 (?)", year: 1968, approx: true },
      father: "josefM", mother: "mariannaN",
      notes: ["Úmrtí 1968 jen podle stromu na Geni (neověřeno)."],
      sources: ["MZA Brno, N 4475 str. 126"] },
    { id: "jan1861", name: "Jan Pacík", line: "pacik", cert: "M",
      b: { date: "30. 12. 1861", year: 1861, place: "Nedašova Lhota č. 5" },
      d: { date: "1. 5. 1912", year: 1912, place: "Nedašova Lhota č. 5" },
      father: "matej1832", mother: "mariannaK", occ: "domkář",
      marriage: "11. 7. 1887 – s Františkou Tomečkovou; 2. sňatek 1901 s Annou Valentovou z Poteče (*16. 4. 1872, †4. 1. 1935)",
      notes: ["Zemřel na zánět plic.", "Děti z 1. manželství: Jan 1888, Maria 1890, Ludvík 1891, František 1892, Alois 1894, Jan 1897, Františka 1899."],
      sources: ["MZA N 4481; O 4489; Z 4496"] },
    { id: "frantiskaT", name: "Františka Pacíková", maiden: "Tomečková", line: "pacik", cert: "M",
      b: { date: "12. 9. 1862", year: 1862, place: "Nedašova Lhota" },
      d: { date: "12. 7. 1899", year: 1899, place: "Nedašova Lhota č. 5" },
      father: "frantisekT1819", mother: "annaB",
      notes: ["Zemřela na otravu krve (gangréna ruky)."], sources: ["MZA N 4481; Z 4495"] },
    { id: "matej1832", name: "Matěj Pacík", line: "pacik", cert: "M",
      b: { date: "17. 3. 1832", year: 1832, place: "Nedašova Lhota" },
      d: { date: "18. 10. 1903", year: 1903, place: "Nedašova Lhota č. 5" },
      father: "josef1798", mother: "veronikaV", occ: "domkář, tkadlec",
      marriage: "5. 5. 1856 – s Mariannou Kolínkovou", sources: ["MZA N 4481; O 4489; Z 4496"] },
    { id: "mariannaK", name: "Marianna Pacíková", maiden: "Kolínková", line: "pacik", cert: "M",
      b: { date: "cca 1830", year: 1830, approx: true, place: "Nedašova Lhota" },
      father: "josefK1797", mother: "katerinaM" },
    { id: "frantisekT1819", name: "František Tomeček", line: "pacik", cert: "M",
      b: { date: "16. 2. 1819", year: 1819, place: "Nedašova Lhota č. 6" },
      father: "janT", mother: "mariannaF", occ: "domkář / podsedník",
      marriage: "25. 2. 1851 – s Annou Bartošákovou (dispens pro příbuzenství 3. stupně)" },
    { id: "annaB", name: "Anna Tomečková", maiden: "Bartošáková", line: "pacik", cert: "M",
      b: { date: "cca 1826", year: 1826, approx: true, place: "Nedašova Lhota" },
      father: "vaclavB", mother: "mariannaVn" },
    { id: "josef1798", name: "Josef Pacík", line: "pacik", cert: "M",
      b: { date: "2. 2. 1798", year: 1798, place: "Nedašova Lhota č. 5" },
      father: "matous1760", mother: "marinaM", occ: "domkář",
      marriage: "24. 1. 1826 – s Veronikou Vaňkovou", sources: ["MZA N 4473; O 4489"] },
    { id: "veronikaV", name: "Veronika Pacíková", maiden: "Vaňková", line: "pacik", cert: "M",
      b: { date: "cca 1804", year: 1804, approx: true }, father: "tomasV" },
    { id: "tomasV", name: "Tomáš Vaněk", line: "pacik", cert: "M",
      b: { date: "?", year: 1770, approx: true }, occ: "domkář v Nedašově Lhotě" },
    { id: "josefK1797", name: "Josef Kolínek", line: "pacik", cert: "M",
      b: { date: "9. 2. 1797", year: 1797, place: "Nedašova Lhota č. 60" },
      father: "jakubK", mother: "marinaA", occ: "domkář",
      marriage: "25. 2. 1821 – s Kateřinou Měřičkovou" },
    { id: "katerinaM", name: "Kateřina Kolínková", maiden: "Měřičková", line: "pacik", cert: "M",
      b: { date: "cca 1793", year: 1793, approx: true }, notes: ["Nemanželská dcera Kateřiny Měřičkové."] },
    { id: "jakubK", name: "Jakub Kolínek", line: "pacik", cert: "M",
      b: { date: "cca 1760", year: 1760, approx: true }, occ: "podruh", marriage: "16. 9. 1787 – s Marinou Adamkovou(?)" },
    { id: "marinaA", name: "Marina Kolínková", maiden: "Adamková (?)", line: "pacik", cert: "M",
      b: { date: "cca 1765", year: 1765, approx: true } },
    { id: "janT", name: "Jan Tomeček", line: "pacik", cert: "M",
      b: { date: "cca 1777", year: 1777, approx: true }, occ: "sedlák", marriage: "6. 10. 1800 – s Mariannou Fojtíkovou" },
    { id: "mariannaF", name: "Marianna Tomečková", maiden: "Fojtíková", line: "pacik", cert: "M",
      b: { date: "cca 1782", year: 1782, approx: true }, notes: ["Dcera sedláka Martina Fojtíka."] },
    { id: "vaclavB", name: "Václav Bartošák", line: "pacik", cert: "M",
      b: { date: "cca 1798", year: 1798, approx: true }, occ: "podsedník", marriage: "5. 2. 1822 – s Mariannou Vaňkovou",
      notes: ["Syn sedláka Josefa Bartošáka."] },
    { id: "mariannaVn", name: "Marianna Bartošáková", maiden: "Vaňková", line: "pacik", cert: "M",
      b: { date: "cca 1802", year: 1802, approx: true }, notes: ["Dcera sedláka Pavla Vaňka."] },
    { id: "matous1760", name: "Matouš Pacík (Fojtík)", line: "pacik", cert: "M",
      b: { date: "6. 9. 1760 (křest)", year: 1760, place: "Nedašova Lhota" },
      father: "tobias", mother: "katerinaX", occ: "tkadlec, Nedašova Lhota č. 5",
      marriage: "1784 – s Marinou Markovou („Mathaeus filius defuncti Tobiae Fojtik“)",
      sources: ["MZA Brumov sign. 4012, img 6 a 200"] },
    { id: "marinaM", name: "Marina Pacíková", maiden: "Marková", line: "pacik", cert: "M",
      b: { date: "29. 6. 1761 (křest)", year: 1761, place: "Nedašov" }, father: "janMarek",
      sources: ["MZA 4012 img 9"] },
    { id: "janMarek", name: "Jan Marek", line: "pacik", cert: "M",
      b: { date: "?", year: 1730, approx: true, place: "Nedašov" }, d: { date: "před 1784", year: 1784, approx: true } },
    { id: "tobias", name: "Tobiáš Pacík (Fojtík)", line: "pacik", cert: "M",
      b: { date: "cca 1712", year: 1712, approx: true },
      d: { date: "16. 4. 1779", year: 1779, place: "Nedašova Lhota č. 5" },
      occ: "mlynář (molitor)",
      notes: ["Nejstarší doložený předek po meči. Zemřel ve věku 67 let.", "V matrikách psán Pazik / Pačík i Fojtík – rod Pacíků se v 18. století psal Fojtík.", "Manželka Kateřina (žila 1779)."],
      sources: ["MZA Brumov sign. 4012, img 262"] },
    { id: "katerinaX", name: "Kateřina Pacíková", line: "pacik", cert: "M",
      b: { date: "?", year: 1720, approx: true } },

    // ── Matůšů ─────────────────────────────────────────
    { id: "josefM", name: "Josef Matůšů", line: "matusu", cert: "M",
      b: { date: "17. 3. 1851", year: 1851, place: "Nedašov č. 69" },
      d: { date: "25. 8. 1900", year: 1900, place: "Nedašov č. 64" },
      father: "jiri1813", mother: "annaH", occ: "sedlák / domkář",
      marriage: "1) 12. 1. 1875 s Anežkou Markovou; 2) 10. 2. 1885 s Mariannou Novákovou",
      notes: ["Zemřel na rakovinu žaludku."] },
    { id: "mariannaN", name: "Marianna Matůšů", maiden: "Nováková", line: "matusu", cert: "M",
      b: { date: "29. 9. 1865", year: 1865, place: "Nedašov č. 88" }, father: "vaclavN", mother: "katerinaV" },
    { id: "jiri1813", name: "Jiří Matůšů", line: "matusu", cert: "M",
      b: { date: "19. 8. 1813", year: 1813, place: "Nedašov č. 67" }, father: "jiri1782", mother: "barboraS",
      occ: "sedlák", marriage: "1834/35 – s Annou Holbovou" },
    { id: "annaH", name: "Anna Matůšů", maiden: "Holbová", line: "matusu", cert: "M",
      b: { date: "10. 5. 1812", year: 1812, place: "Nedašov č. 64" },
      notes: ["Dcera Josefa Holby, kováře (později sedláka), a Mariny Fojtíkové (dcery Jiřího Fojtíka)."] },
    { id: "vaclavN", name: "Václav Novák", line: "matusu", cert: "M",
      b: { date: "cca 1818", year: 1818, approx: true, place: "Nedašov" }, occ: "podsedník",
      marriage: "3. 2. 1842 – s Kateřinou Vaculíkovou",
      notes: ["Syn Martina Nováka, čtvrtláníka, a Anny roz. Belej(?)."] },
    { id: "katerinaV", name: "Kateřina Nováková", maiden: "Vaculíková", line: "matusu", cert: "M",
      b: { date: "cca 1824", year: 1824, approx: true, place: "Nedašov č. 88" },
      notes: ["Dcera Josefa Vaculíka, čtvrtláníka v Nedašově č. 88, a Ludmily(?) roz. Kopečné(?)."] },
    { id: "jiri1782", name: "Jiří Matůšů st.", line: "matusu", cert: "M",
      b: { date: "31. 3. 1782 (křest)", year: 1782, place: "Nedašov č. 67" },
      occ: "sedlák", marriage: "25. 1. 1802 – s Barborou Šaurkovou(?) z Bylnice",
      notes: ["Rodiče: Jiří Matůšů, sedlák, a Marina (Nedašov č. 67)."] },
    { id: "barboraS", name: "Barbora Matůšů", maiden: "Šaurková (?)", line: "matusu", cert: "M",
      b: { date: "cca 1782", year: 1782, approx: true, place: "Bylnice" },
      notes: ["Dcera Mikuláše Šaurka(?), sedláka v Bylnici."] },

    // ── Struž ──────────────────────────────────────────
    { id: "margareta", name: "Margareta Pacíková", maiden: "Stružová", line: "struz", cert: "D",
      b: { date: "20. 12. 1937", year: 1937, place: "pravděpodobně Opava" },
      d: { date: "28. 11. 2016", year: 2016, place: "Ostrava" },
      father: "arnost", mother: "marieJ",
      notes: ["Pohřbena v Chuchelné.", "Sourozenci: Anežka Manová (*22. 1. 1951 Opava), Erich, sestra zemřelá jako dítě za války."] },
    { id: "arnost", name: "Arnošt Struž (Ernst Strusch)", line: "struz", cert: "M",
      b: { date: "3. 12. 1907", year: 1907, place: "Chuchelná" },
      d: { date: "18. 10. 1999", year: 1999, place: "Chuchelná č. 160" },
      father: "karlS", mother: "antonia", occ: "strojní zámečník",
      notes: ["1950 bydlel Chuchelná č. 105.", "Voják 1940–41 (Hultschiner Soldaten); po válce odsouzen lidovým soudem k 1 roku a konfiskaci části majetku."],
      sources: ["Standesamt Kuchelna N 1907 Nr. 56 – ZA Opava"] },
    { id: "karlS", name: "Karl Strusch", line: "struz", cert: "M",
      b: { date: "?", year: 1880, approx: true }, occ: "panský zahradník v Chuchelné",
      notes: ["Sňatek s Antonií Komárkovou není v Chuchelné 1895–1907.", "Kandidáti na otce: Anton Strusch (*1833, syn Mikuláše Struše) nebo Jakob Strusch – neověřeno."] },
    { id: "antonia", name: "Antonie Strusch", maiden: "Komárková (Komarek)", line: "struz", cert: "M",
      b: { date: "?", year: 1882, approx: true }, notes: ["Možní rodiče: Komárkové oddaní v Chuchelné 1880 (Franz, Anton) – neověřeno."] },

    // ── Jiřík / Opoloný ────────────────────────────────
    { id: "marieJ", name: "Marie Stružová", maiden: "Jiříková (Irzik)", line: "jirik", cert: "M",
      b: { date: "9. 9. 1914", year: 1914, place: "Chuchelná" },
      d: { date: "cca 1978", year: 1978, approx: true, place: "Opava" },
      father: "rudolfI", mother: "marieO",
      notes: ["Nejstarší z 9 dětí (paměti sestry Antonie Jiříkové): Jiří, Ludvina, Helena, Anna, Antonie, Adolf 1925, Rudolf 1926, Robert 1928.", "Švadlena, od 17 let v tabákovně."],
      sources: ["Standesamt Kuchelna N 1914 Nr. 34"] },
    { id: "rudolfI", name: "Rudolf Jiřík (Irzik)", line: "jirik", cert: "M",
      b: { date: "17. 4. 1882", year: 1882, place: "Bolatice" },
      father: "franzI", mother: "marieH", occ: "zedník, později výrobce cementového zboží",
      marriage: "24. 1. 1910, Chuchelná – s Marií Opolony",
      notes: ["Chuchelná č. 75; velitel hasičů, člen místní školní rady."],
      sources: ["Standesamt Bolatice N 1882 Nr. 29; Kuchelna O 1910 Nr. 2"] },
    { id: "marieO", name: "Marie Jiříková", maiden: "Opolony (Opoloná)", line: "opolony", cert: "M",
      b: { date: "30. 6. 1885", year: 1885, place: "Chuchelná" },
      father: "antonO", mother: "rosalie",
      notes: ["Bratr pravděpodobně kovář Adolf Opoloný (starosta 1931)."], sources: ["Kuchelna N 1885 Nr. 18"] },
    { id: "franzI", name: "Franz Irzik", line: "jirik", cert: "M",
      b: { date: "?", year: 1850, approx: true }, occ: "domkář, 1910 řeznický mistr v Bolaticích",
      notes: ["Sňatek s Marií Herudek není v civilních matrikách Bolatic 1874–1881 – uzavřen dříve, jen církevně.", "Kandidát na rodinu: Franz Irzik × Carolina Scholtis (syn Valentina Irzika z Henneberku), Bolatice 1844 – neověřeno."] },
    { id: "marieH", name: "Marie Irzik", maiden: "Herudek", line: "jirik", cert: "M",
      b: { date: "?", year: 1852, approx: true }, d: { date: "před 1910", year: 1910, approx: true } },
    { id: "antonO", name: "Anton Opolony", line: "opolony", cert: "M",
      b: { date: "?", year: 1850, approx: true }, occ: "kovářský mistr v Chuchelné",
      notes: ["Sňatek není v Chuchelné 1874–1884 – pravděpodobně před 1874 ve farnosti Krzanowice (PL)."] },
    { id: "rosalie", name: "Rosalie Opolony", maiden: "Cz…kowsky (?)", line: "opolony", cert: "M",
      b: { date: "?", year: 1855, approx: true }, notes: ["Rodné příjmení čteno nejistě („Czeikowsky“ / „Czilakowsky“)."] }
  ]
};
